name=input("Enter Your Name:")
print(name.lower())
print(name.upper())
print(name.title())
print(name.capitalize())
print(name.swapcase())
print(len(name))
print(name.split())
print(name.find("S"))
print(name.count("a"))
print(name.replace("s","a"))
print(name.strip())
print(name.lstrip())
print(name.rstrip())
print(name.center(50))
print(name.ljust(80))
print(name.rjust(80))